### ISSUE TITLE
No version for `cilium-cli v0.16.16`

### ISSUE THREAD

**Issue by lucasfcnunes** [cilium/cilium-cli#2774]
## Bug report

**General Information**

- Cilium CLI version (run `cilium version`): NA
- Orchestration system version in use (e.g. `kubectl version`, ...): NA
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions): NA
- Link to relevant artifacts (policies, deployments scripts, ...): NA
- Generate and upload a system zip: `cilium sysdump`: NA

**How to reproduce the issue**

1. `wget -O - https://github.com/cilium/cilium-cli/releases/download/v0.16.16/cilium-linux-amd64.tar.gz | tar -xvz -f - 'cilium' && ./cilium version --client`
2. 
```
cilium-cli:  compiled with go1.23.0 on linux/amd64
cilium image (default): v1.16.0
cilium image (stable): v1.16.1
```
3. Assert there's no version for `cilium-cli`

**Comment by cyanidium** [comment]
Not sure if it's related, but `https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt` is still showing v0.16.15 as the current version as well.

**Comment by lucasfcnunes** [comment]
@viktor-kurchenko PING

**Comment by viktor-kurchenko** [comment]
@michi-covalent I think this bug has been [fixed](https://github.com/cilium/cilium-cli/commit/1595a018c9a8d84ce173ba52b722bab81037c790) by @chenrui333.
Can we release a new version with fix?

**Comment by lucasfcnunes** [comment]
Still no new release made patching this issue :(

**Comment by michi-covalent** [comment]
we'll cut a new release at the same time as cilium v1.16 patch release. it typically happens mid month around 15th 🚀🙏

**Comment by matihost** [comment]
Seems fixed with v0.16.17

**Comment by lucasfcnunes** [comment]
> Seems fixed with v0.16.17

Thanks for the follow up. I'm checking right now. :)

**Comment by lucasfcnunes** [comment]
All resolved on `v0.16.17`!

![image](https://github.com/user-attachments/assets/568a7fb4-a57b-418c-96a0-444ec070ad4a)

**Comment by cyanidium** [comment]
> Not sure if it's related, but `https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt` is still showing v0.16.15 as the current version as well.

The `stable.txt` file is still showing .15 instead of .17, is that intentional? It means the [provided install instructions](https://github.com/cilium/cilium-cli?tab=readme-ov-file#installation) give an out-of-date version.

**Comment by lucasfcnunes** [comment]
Maybe it's intentional - `stable` and `latest`, in some projects, are really not the same thing. We can even say something like `latest stable`, `latest active LTS` and `latest nightly` builds

e.g.
- [GKE](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#:~:text=Get%20the%20latest%20Kubernetes%20release)
![image](https://github.com/user-attachments/assets/abfe65ba-6d39-4928-8649-47b3c73b93e5)
- [nodejs](https://nodejs.org/en/about/previous-releases#:~:text=Production%20applications%20should%20only%20use%20Active%20LTS%20or%20Maintenance%20LTS%20releases.)
![image](https://github.com/user-attachments/assets/992a2222-0c3e-4c4a-bc89-8716033f85a6)
